sonar.projectName=Boilerplate
sonar.sourceEncoding=UTF-8

sonar.sources=apps,packages,scripts,infra,drizzle,.github
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.spec.ts,**/*.test.ts,**/*.test.tsx,apps/api/test/**,apps/ai/**/*.egg-info/**,scripts/debug/**

sonar.tests=apps/api/src,apps/api/test,apps/web/src,packages,tests
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/*.test.tsx,apps/api/test/**/*.e2e-spec.ts,tests/**/*.js
