#!/bin/sh
set -eu

dashboard_time_from="${GRAFANA_DASHBOARD_TIME_FROM:-now-24h}"
mkdir -p /var/lib/grafana/dashboards

# Render every provisioned dashboard (api-overview.json plus any generated by
# scripts/generators/generate-grafana-dashboard.js).
for src in /etc/grafana/provisioning/dashboards/json/*.json; do
  [ -e "$src" ] || continue
  dest="/var/lib/grafana/dashboards/$(basename "$src")"
  sed "s|__GRAFANA_DASHBOARD_TIME_FROM__|${dashboard_time_from}|g" "$src" > "$dest"

  if grep -q '__GRAFANA_DASHBOARD_TIME_FROM__' "$dest"; then
    echo "Grafana dashboard time placeholder was not rendered in $(basename "$src")" >&2
    exit 1
  fi
done

if [ -f /var/lib/grafana/grafana.db ] && [ -n "${GF_SECURITY_ADMIN_PASSWORD:-}" ]; then
  grafana cli \
    --homepath /usr/share/grafana \
    --config /etc/grafana/grafana.ini \
    admin reset-admin-password "$GF_SECURITY_ADMIN_PASSWORD"
fi

exec /run.sh
